### ISSUE TITLE
Webkit 1.0 is dead for Debian systems. Please change detection to Webkit 2.0

### ISSUE THREAD

**Issue by offternet** [step-/yad#8]
Webkit 1.x  on a Debian system is no longer possible: 

I have spent many hours trying to locate and install all the dependicies required to properly install webkit 1.x on my Debian systems and it can no longer be accomplished as webkit 1.x is no longer supported by Debian (maintainers). 

Additionally, I have seen where  Webkit 2.0 will work with GTK2.x .  

How would I modify your configure.ac to detect newer version webkit 2.0 ? 

My goal ultimately is to document the compiling process of your yadL 0.42.81 with html, sourceview and standalone options:  ./configure --enable-html --enable-sourceview --enable-standalone.  

Thanks in advace :)

**Comment by step-** [comment]
Hi again.

> How would I modify your configure.ac to detect newer version webkit 2.0 ?

Edit configure.ac. Locate the `case "$with_gtk"` statement. Copy the `WEBKIT=` line from the `gtk3)` section down to the `gtk2)` section.

Don't let me stop you from trying, but I don't think that this will get you a GTK2 binary that works with Webkit2. The reason is that Webkit2 needs GTK3. Take a look at this SO thread <https://stackoverflow.com/questions/19692818/webkitgtk-gtk2-gtk3/19695900>.

> Additionally, I have seen where Webkit 2.0 will work with GTK2.x .

I don't know what you mean by that.

**Comment by offternet** [comment]
Thank you for info on moding configure.ac for webkit2 detection and about needing GTK3. Still want to test possibilities.
